"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  createPatientWithHistory,
  createExamination,
} from "@/lib/patients";
import { fieldClass, primaryButtonClass } from "./staffStyles";
import DiagnosticTests from "./DiagnosticTests";
import PatientConsent from "./PatientConsent";

// Radio and checkbox rows. On touch screens the whole label grows to 44px
// so a finger can hit the option text, not just the small box.
const choiceInputClass = "h-5 w-5 shrink-0 accent-[#00685F]";
const choiceLabelClass = "flex items-center gap-2 pointer-coarse:min-h-11 pointer-coarse:pr-2";

const MEDICAL_CONDITIONS = [
  "Rheumatic Heart Disease",
  "Asthma",
  "Stomach Ulcer",
  "Liver Disease",
  "Hypertension",
  "Coronary Artery Disease",
  "Diabetes",
  "Kidney Disease",
  "Persistent Cough",
  "Hypotension",
  "Stroke(CVA)",
  "Arthritis",
  "STD",
  "Pregnant(For Women)",
];

const EMPTY_PROFILE = {
  fullName: "",
  email: "",
  birthDate: "",
  age: "",
  sex: "",
  contactNumber: "",
  address: "",
  occupation: "",
  civilStatus: "",
  nationality: "",
  religion: "",
};

const EMPTY_HISTORY = {
  chiefComplaint: "",
  presentIllness: "",
  conditions: [],
  takesMedication: "",
  medicationDetails: "",
  gumsBleed: "",
  smokes: "",
  sticksPerDay: "",
  hasAllergies: "",
  allergyDetails: "",
  hadProphylaxis: "",
  prophylaxisWhen: "",
  hadExtraction: "",
  extractionWhen: "",
  dentureType: "",
};

const EMPTY_EXAM = {
  bloodPressure: "",
  respiratoryRate: "",
  pulseRate: "",
  temperature: "",
  headNormal: false,
  headNotes: "",
  eyesNormal: false,
  eyesNotes: "",
  tmjNormal: false,
  tmjNotes: "",
  lipsNormal: false,
  lipsNotes: "",
  palateNormal: false,
  palateNotes: "",
  tongueNormal: false,
  tongueNotes: "",
  mouthFloorNormal: false,
  mouthFloorNotes: "",
  molarRelationship: "",
  canineRelationship: "",
  occlusionClassification: "",
  gingiva: "",
  gingivaColor: "",
  gingivaConsistency: "",
  oralHygiene: "",
  hygieneSeverity: "",
  softDeposits: "",
  hardDeposits: "",
};

// patientId (uuid) is generated by the page on the server so step 2 can link
// to the patient. The record number shown to staff is assigned by the
// database when step 1 saves.
export default function AddPatient({ patientId }) {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [profile, setProfile] = useState(EMPTY_PROFILE);
  const [history, setHistory] = useState(EMPTY_HISTORY);
  const [exam, setExam] = useState(EMPTY_EXAM);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);
  const [recordNumber, setRecordNumber] = useState(null);
  // Bumped by "Discard changes" on the diagnostic tests step so the form
  // remounts empty (DiagnosticTests keeps its own state).
  const [diagnosticsKey, setDiagnosticsKey] = useState(0);

  const handleProfileChange = (e) => {
    const { name, value } = e.target;
    setProfile((prev) => ({ ...prev, [name]: value }));
    setError(null);
  };

  const handleHistoryChange = (e) => {
    const { name, value } = e.target;
    setHistory((prev) => ({ ...prev, [name]: value }));
  };

  const handleConditionToggle = (condition) => {
    setHistory((prev) => {
      const isChecked = prev.conditions.includes(condition);
      const conditions = isChecked
        ? prev.conditions.filter((item) => item !== condition)
        : [...prev.conditions, condition];
      return { ...prev, conditions };
    });
  };

  const handleExamChange = (e) => {
    const { name, value, type, checked } = e.target;
    setExam((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));
    setError(null);
  };

  const handleSubmitIntake = async () => {
    if (!profile.fullName.trim()) {
      setError("Enter the patient's full name before submitting.");
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const patient = await createPatientWithHistory(patientId, profile, history);
      setRecordNumber(patient.patient_id);
      setStep(2);
    } catch (err) {
      if (err.code === "23505") {
        setError("A patient with this email already exists.");
      } else {
        setError("Patient wasn't saved. Check your connection and try again.");
      }
    } finally {
      setSaving(false);
    }
  };

  const handleSaveExamination = async () => {
    setSaving(true);
    setError(null);
    try {
      await createExamination(patientId, exam);
      setStep(4);
    } catch {
      setError(
        "Examination wasn't saved. Vital signs must be numbers (e.g. 72, 36.5).",
      );
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="bg-white w-full p-4 pt-2 pb-6">
      <div className="flex flex-col justify-between">
        <div>
          <h1 className="text-3xl sm:text-4xl font-bold">Add New Patient</h1>
          <p className="text-gray-500">
            Complete the patient profiling form below to register a new clinical
            record.
          </p>
        </div>
        <div className="border w-full border-gray-300 overflow-hidden mt-2 rounded-lg">
          <div className="bg-blue-200 flex flex-wrap gap-2 items-center justify-between border border-gray-300 p-2 rounded-t-lg">
            <h1 className="text-[#00685F] text-xl sm:text-2xl font-bold">
              Patient&apos;s Information Form
            </h1>
            <span className="bg-white border border-gray-300 rounded-lg px-2 py-1 text-sm text-gray-500">
              Rec: #{recordNumber || " assigned on save"}
            </span>
          </div>

          <div className="p-2 mx-2">
            {step === 1 && (
              <>
                <div className="font-bold mt-4">Basic Information</div>
                <hr className="border border-gray-200" />
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 mt-2 gap-4">
                  <div className="flex flex-col gap-1">
                    <label htmlFor="patient-fullName" className="text-sm font-medium">Full Name</label>
                    <input
                      id="patient-fullName"
                      type="text"
                      name="fullName"
                      value={profile.fullName}
                      onChange={handleProfileChange}
                      placeholder="Last, First, M.I."
                      className={fieldClass()}
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <label htmlFor="patient-birthDate" className="text-sm font-medium">Birth Date</label>
                    <input
                      id="patient-birthDate"
                      type="date"
                      name="birthDate"
                      value={profile.birthDate}
                      onChange={handleProfileChange}
                      className={fieldClass()}
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <label htmlFor="patient-age" className="text-sm font-medium">Age</label>
                    <input
                      id="patient-age"
                      type="number"
                      name="age"
                      min="1"
                      max="120"
                      value={profile.age}
                      onChange={handleProfileChange}
                      placeholder="0"
                      className={fieldClass()}
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <label htmlFor="patient-sex" className="text-sm font-medium">Sex</label>
                    <select
                      id="patient-sex"
                      name="sex"
                      value={profile.sex}
                      onChange={handleProfileChange}
                      className={fieldClass()}
                    >
                      <option value="">Select</option>
                      <option value="male">Male</option>
                      <option value="female">Female</option>
                    </select>
                  </div>
                </div>

                <div className="flex flex-col md:flex-row gap-4 mt-4">
                  <div className="flex flex-col gap-1 w-full md:w-72">
                    <label htmlFor="patient-contactNumber" className="text-sm font-medium">Tel/CP No.</label>
                    <input
                      id="patient-contactNumber"
                      type="tel"
                      inputMode="tel"
                      autoComplete="tel"
                      name="contactNumber"
                      value={profile.contactNumber}
                      onChange={handleProfileChange}
                      placeholder="09XX-XXX-XXXX"
                      className={fieldClass()}
                    />
                  </div>
                  <div className="flex flex-col gap-1 w-full md:w-72">
                    <label htmlFor="patient-email" className="text-sm font-medium">
                      Email (optional)
                    </label>
                    <input
                      id="patient-email"
                      type="email"
                      name="email"
                      value={profile.email}
                      onChange={handleProfileChange}
                      placeholder="name@example.com"
                      className={fieldClass()}
                    />
                  </div>
                  <div className="flex flex-col gap-1 flex-1">
                    <label htmlFor="patient-address" className="text-sm font-medium">Complete Address</label>
                    <input
                      id="patient-address"
                      type="text"
                      name="address"
                      value={profile.address}
                      onChange={handleProfileChange}
                      placeholder="Street, City, State, Zip"
                      className={fieldClass()}
                    />
                  </div>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 mt-2 gap-4">
                  <div className="flex flex-col gap-1">
                    <label htmlFor="patient-occupation" className="text-sm font-medium">Occupation</label>
                    <input
                      id="patient-occupation"
                      type="text"
                      name="occupation"
                      value={profile.occupation}
                      onChange={handleProfileChange}
                      className={fieldClass()}
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <label htmlFor="patient-civilStatus" className="text-sm font-medium">Civil Status</label>
                    <select
                      id="patient-civilStatus"
                      name="civilStatus"
                      value={profile.civilStatus}
                      onChange={handleProfileChange}
                      className={fieldClass()}
                    >
                      <option value="">Select</option>
                      <option value="single">Single</option>
                      <option value="married">Married</option>
                      <option value="widowed">Widowed</option>
                      <option value="separated">Separated</option>
                    </select>
                  </div>

                  <div className="flex flex-col gap-1">
                    <label htmlFor="patient-nationality" className="text-sm font-medium">Nationality</label>
                    <input
                      id="patient-nationality"
                      type="text"
                      name="nationality"
                      value={profile.nationality}
                      onChange={handleProfileChange}
                      className={fieldClass()}
                    />
                  </div>
                  <div className="flex flex-col gap-1">
                    <label htmlFor="patient-religion" className="text-sm font-medium">Religion</label>
                    <input
                      id="patient-religion"
                      type="text"
                      name="religion"
                      value={profile.religion}
                      onChange={handleProfileChange}
                      className={fieldClass()}
                    />
                  </div>
                </div>
                <div className="font-bold mt-4">Chief Complaint</div>
                <hr className="border border-gray-200" />
                <div className="flex flex-col md:flex-row gap-4 mt-2">
                  <div className="flex flex-col gap-1 flex-1">
                    <label htmlFor="patient-chiefComplaint" className="text-sm font-medium">
                      CHIEF COMPLAINT (Patient&apos;s own words)
                    </label>
                    <input
                      id="patient-chiefComplaint"
                      type="text"
                      name="chiefComplaint"
                      value={history.chiefComplaint}
                      onChange={handleHistoryChange}
                      className={fieldClass()}
                    />
                  </div>
                  <div className="flex flex-col gap-1 flex-1">
                    <label htmlFor="patient-presentIllness" className="text-sm font-medium">
                      History of Present Illness
                    </label>
                    <input
                      id="patient-presentIllness"
                      type="text"
                      name="presentIllness"
                      value={history.presentIllness}
                      onChange={handleHistoryChange}
                      className={fieldClass()}
                    />
                  </div>
                </div>
                <div className="font-bold mt-4">Medical History</div>
                <hr className="border border-gray-200" />
                <div className="bg-[#EFF4FF] border-gray-200 p-4 mt-2 rounded-lg">
                  <label className="text-sm font-medium">
                    Check all conditions that apply to the patient:
                  </label>
                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3 sm:gap-4 mt-3">
                    {MEDICAL_CONDITIONS.map((condition) => (
                      <label key={condition} className="flex flex-wrap items-center gap-2 pointer-coarse:min-h-11">
                        <input
                          type="checkbox"
                          className={choiceInputClass}
                          checked={history.conditions.includes(condition)}
                          onChange={() => handleConditionToggle(condition)}
                        />{" "}
                        {condition}
                      </label>
                    ))}
                  </div>
                </div>
                <div className="flex flex-col gap-3 mt-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <label className="text-sm font-medium">
                      1. Are you under any medication/s?
                    </label>
                    <label className={choiceLabelClass}>
                      <input
                        type="radio"
                        className={choiceInputClass}
                        name="takesMedication"
                        value="yes"
                        checked={history.takesMedication === "yes"}
                        onChange={handleHistoryChange}
                      />{" "}
                      Yes
                    </label>
                    <label className={choiceLabelClass}>
                      <input
                        type="radio"
                        className={choiceInputClass}
                        name="takesMedication"
                        value="no"
                        checked={history.takesMedication === "no"}
                        onChange={handleHistoryChange}
                      />{" "}
                      No
                    </label>
                    <input
                      id="patient-medicationDetails"
                      aria-label="Medication details"
                      type="text"
                      name="medicationDetails"
                      value={history.medicationDetails}
                      onChange={handleHistoryChange}
                      placeholder="If yes, please specify"
                      className="border-b border-gray-300 outline-none ml-2 flex-1 min-w-40"
                    />
                  </div>

                  <div className="flex flex-wrap items-center gap-2">
                    <label className="text-sm font-medium">
                      2. Do your gums bleed easily when brushing?
                    </label>
                    <label className={choiceLabelClass}>
                      <input
                        type="radio"
                        className={choiceInputClass}
                        name="gumsBleed"
                        value="yes"
                        checked={history.gumsBleed === "yes"}
                        onChange={handleHistoryChange}
                      />{" "}
                      Yes
                    </label>
                    <label className={choiceLabelClass}>
                      <input
                        type="radio"
                        className={choiceInputClass}
                        name="gumsBleed"
                        value="no"
                        checked={history.gumsBleed === "no"}
                        onChange={handleHistoryChange}
                      />{" "}
                      No
                    </label>
                  </div>

                  <div className="flex flex-wrap items-center gap-2">
                    <label className="text-sm font-medium">3. Do you smoke?</label>
                    <label className={choiceLabelClass}>
                      <input
                        type="radio"
                        className={choiceInputClass}
                        name="smokes"
                        value="yes"
                        checked={history.smokes === "yes"}
                        onChange={handleHistoryChange}
                      />{" "}
                      Yes
                    </label>
                    <label className={choiceLabelClass}>
                      <input
                        type="radio"
                        className={choiceInputClass}
                        name="smokes"
                        value="no"
                        checked={history.smokes === "no"}
                        onChange={handleHistoryChange}
                      />{" "}
                      No
                    </label>
                    <input
                      id="patient-sticksPerDay"
                      aria-label="Sticks per day"
                      type="number"
                      name="sticksPerDay"
                      min="0"
                      value={history.sticksPerDay}
                      onChange={handleHistoryChange}
                      placeholder="If yes, how many sticks per day?"
                      className="border-b border-gray-300 outline-none sm:ml-2 w-full sm:w-58"
                    />
                  </div>

                  <div className="flex flex-wrap items-center gap-2">
                    <label className="text-sm font-medium">
                      4. Do you have any known ALLERGY/ies?
                    </label>
                    <label className={choiceLabelClass}>
                      <input
                        type="radio"
                        className={choiceInputClass}
                        name="hasAllergies"
                        value="yes"
                        checked={history.hasAllergies === "yes"}
                        onChange={handleHistoryChange}
                      />{" "}
                      Yes
                    </label>
                    <label className={choiceLabelClass}>
                      <input
                        type="radio"
                        className={choiceInputClass}
                        name="hasAllergies"
                        value="no"
                        checked={history.hasAllergies === "no"}
                        onChange={handleHistoryChange}
                      />{" "}
                      No
                    </label>
                    <input
                      id="patient-allergyDetails"
                      aria-label="Allergy details"
                      type="text"
                      name="allergyDetails"
                      value={history.allergyDetails}
                      onChange={handleHistoryChange}
                      placeholder="If yes, please specify"
                      className="border-b border-gray-300 outline-none ml-2 flex-1 min-w-40"
                    />
                  </div>
                </div>
                <div className="flex gap-8 mt-2">
                  <div className="flex flex-col gap-1 flex-1">
                    <div className="font-bold mt-4">Dental History</div>
                    <hr className="border border-gray-200 w-full" />
                    <div className="flex flex-col gap-2">
                      <div className="flex flex-wrap items-center gap-2">
                        <label className="text-sm font-medium">
                          Previous Oral Prophylaxis
                        </label>
                        <label className={choiceLabelClass}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hadProphylaxis"
                            value="yes"
                            checked={history.hadProphylaxis === "yes"}
                            onChange={handleHistoryChange}
                          />{" "}
                          Yes
                        </label>
                        <label className={choiceLabelClass}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hadProphylaxis"
                            value="no"
                            checked={history.hadProphylaxis === "no"}
                            onChange={handleHistoryChange}
                          />{" "}
                          No
                        </label>
                      </div>
                      <input
                        type="text"
                        name="prophylaxisWhen"
                        value={history.prophylaxisWhen}
                        onChange={handleHistoryChange}
                        placeholder="If yes, when?"
                        className="border-b border-gray-300 outline-none w-full sm:w-58"
                      />
                      <div className="flex flex-wrap items-center gap-2">
                        <label className="text-sm font-medium">
                          Previous Dental Extraction
                        </label>
                        <label className={choiceLabelClass}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hadExtraction"
                            value="yes"
                            checked={history.hadExtraction === "yes"}
                            onChange={handleHistoryChange}
                          />{" "}
                          Yes
                        </label>
                        <label className={choiceLabelClass}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hadExtraction"
                            value="no"
                            checked={history.hadExtraction === "no"}
                            onChange={handleHistoryChange}
                          />{" "}
                          No
                        </label>
                      </div>
                      <input
                        type="text"
                        name="extractionWhen"
                        value={history.extractionWhen}
                        onChange={handleHistoryChange}
                        placeholder="If yes, when?"
                        className="border-b border-gray-300 outline-none w-full sm:w-58"
                      />
                      <label htmlFor="patient-dentureType" className="text-sm font-medium">
                        Denture Type (if applicable)
                      </label>
                      <select
                      id="patient-dentureType"
                        name="dentureType"
                        value={history.dentureType}
                        onChange={handleHistoryChange}
                        className="pointer-coarse:min-h-11 bg-[#F0FDFA] border border-gray-300 rounded-lg px-3 py-2"
                      >
                        <option value="">Select</option>
                        <option value="none">None</option>
                        <option value="partial">Partial</option>
                        <option value="full">Full</option>
                      </select>
                    </div>
                  </div>
                </div>
              </>
            )}
            {step === 2 && (
              <div className="flex flex-col items-center justify-center py-24 gap-4">
                <h2 className="text-2xl font-bold text-[#00685F]">
                  Thank you for sharing your information
                </h2>
                <p className="text-gray-500">
                  Please wait for the dentist to continue your examination.
                </p>
                <button
                  type="button"
                  onClick={() => setStep(3)}
                  className="rounded-lg bg-[#00685F] px-6 py-3 text-sm font-medium text-white hover:bg-[#004c4a]"
                >
                  Begin Vital Signs &amp; Intraoral Examination
                </button>
              </div>
            )}
            {step === 3 && (
              <>
                <div className="flex flex-col gap-1 flex-1">
                  <div className="font-bold mt-4">Clinical / Vital Signs</div>
                  <hr className="border border-gray-200 w-full" />
                  <div className="flex flex-col sm:flex-row gap-4">
                    <div className="flex flex-col flex-1">
                      <label htmlFor="patient-bloodPressure" className="text-sm font-medium">
                        Blood Pressure(mmHg)
                      </label>
                      <input
                      id="patient-bloodPressure"
                        type="text"
                        name="bloodPressure"
                        value={exam.bloodPressure}
                        onChange={handleExamChange}
                        placeholder="120/80"
                        className={fieldClass()}
                      />
                      <label htmlFor="patient-respiratoryRate" className="text-sm font-medium">
                        Respiratory Rate (cpm)
                      </label>
                      <input
                      id="patient-respiratoryRate"
                        type="number"
                        name="respiratoryRate"
                        min="1"
                        value={exam.respiratoryRate}
                        onChange={handleExamChange}
                        placeholder="16"
                        className={fieldClass()}
                      />
                    </div>

                    <div className="flex flex-col  flex-1">
                      <label htmlFor="patient-pulseRate" className="text-sm font-medium">
                        Pulse Rate (bpm)
                      </label>
                      <input
                      id="patient-pulseRate"
                        type="number"
                        name="pulseRate"
                        min="1"
                        value={exam.pulseRate}
                        onChange={handleExamChange}
                        placeholder="72"
                        className={fieldClass()}
                      />
                      <label htmlFor="patient-temperature" className="text-sm font-medium">
                        Temperature (°C)
                      </label>
                      <input
                      id="patient-temperature"
                        type="number"
                        name="temperature"
                        step="0.1"
                        value={exam.temperature}
                        onChange={handleExamChange}
                        placeholder="36.5"
                        className={fieldClass()}
                      />
                    </div>
                  </div>
                  <div className="font-bold mt-4">Extraoral</div>
                  <hr className="border border-gray-200 w-full" />
                  <div className="flex flex-col gap-2 mt-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <label className="w-16">Head:</label>
                      <label className={choiceLabelClass}>
                        <input
                          type="checkbox"
                          className={choiceInputClass}
                          name="headNormal"
                          checked={exam.headNormal}
                          onChange={handleExamChange}
                        />{" "}
                        Normal
                      </label>
                      <label htmlFor="patient-headNotes" className="text-sm font-medium">
                        Abnormality, specify
                      </label>
                      <input
                      id="patient-headNotes"
                        type="text"
                        name="headNotes"
                        value={exam.headNotes}
                        onChange={handleExamChange}
                        className="border-b border-gray-300 outline-none flex-1 min-w-40"
                      />
                    </div>

                    <div className="flex flex-wrap items-center gap-2">
                      <label className="w-16">Eyes:</label>
                      <label className={choiceLabelClass}>
                        <input
                          type="checkbox"
                          className={choiceInputClass}
                          name="eyesNormal"
                          checked={exam.eyesNormal}
                          onChange={handleExamChange}
                        />{" "}
                        Normal
                      </label>
                      <label htmlFor="patient-eyesNotes" className="text-sm font-medium">
                        Abnormality, specify
                      </label>
                      <input
                      id="patient-eyesNotes"
                        type="text"
                        name="eyesNotes"
                        value={exam.eyesNotes}
                        onChange={handleExamChange}
                        className="border-b border-gray-300 outline-none flex-1 min-w-40"
                      />
                    </div>

                    <div className="flex flex-wrap items-center gap-2">
                      <label className="w-16">TMJ:</label>
                      <label className={choiceLabelClass}>
                        <input
                          type="checkbox"
                          className={choiceInputClass}
                          name="tmjNormal"
                          checked={exam.tmjNormal}
                          onChange={handleExamChange}
                        />{" "}
                        Normal
                      </label>
                      <label htmlFor="patient-tmjNotes" className="text-sm font-medium">
                        Abnormality, specify
                      </label>
                      <input
                      id="patient-tmjNotes"
                        type="text"
                        name="tmjNotes"
                        value={exam.tmjNotes}
                        onChange={handleExamChange}
                        className="border-b border-gray-300 outline-none flex-1 min-w-40"
                      />
                    </div>
                  </div>
                </div>

                <div className="font-bold mt-4">Intraoral Examination</div>
                <hr className="border border-gray-200 w-full" />
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-8 mt-2">
                  <div className="flex flex-col gap-3 mt-4">
                    <div className="flex flex-col gap-1">
                      <label className="text-sm font-medium">Lips</label>
                      <div className="flex flex-wrap items-center gap-2">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="checkbox"
                            className={choiceInputClass}
                            name="lipsNormal"
                            checked={exam.lipsNormal}
                            onChange={handleExamChange}
                          />{" "}
                          Normal
                        </label>
                        <label htmlFor="patient-lipsNotes" className="text-sm font-medium">
                          Abnormal, specify
                        </label>
                        <input
                      id="patient-lipsNotes"
                          type="text"
                          name="lipsNotes"
                          value={exam.lipsNotes}
                          onChange={handleExamChange}
                          className="border-b border-gray-300 outline-none flex-1 min-w-40"
                        />
                      </div>
                    </div>

                    <div className="flex flex-col gap-1">
                      <label className="text-sm font-medium">Palate</label>
                      <div className="flex flex-wrap items-center gap-2">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="checkbox"
                            className={choiceInputClass}
                            name="palateNormal"
                            checked={exam.palateNormal}
                            onChange={handleExamChange}
                          />{" "}
                          Normal
                        </label>
                        <label htmlFor="patient-palateNotes" className="text-sm font-medium">
                          Abnormal, specify
                        </label>
                        <input
                      id="patient-palateNotes"
                          type="text"
                          name="palateNotes"
                          value={exam.palateNotes}
                          onChange={handleExamChange}
                          className="border-b border-gray-300 outline-none flex-1 min-w-40"
                        />
                      </div>
                    </div>

                    <div className="flex flex-col gap-1">
                      <label className="text-sm font-medium">Tongue</label>
                      <div className="flex flex-wrap items-center gap-2">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="checkbox"
                            className={choiceInputClass}
                            name="tongueNormal"
                            checked={exam.tongueNormal}
                            onChange={handleExamChange}
                          />{" "}
                          Normal
                        </label>
                        <label htmlFor="patient-tongueNotes" className="text-sm font-medium">
                          Abnormal, specify
                        </label>
                        <input
                      id="patient-tongueNotes"
                          type="text"
                          name="tongueNotes"
                          value={exam.tongueNotes}
                          onChange={handleExamChange}
                          className="border-b border-gray-300 outline-none flex-1 min-w-40"
                        />
                      </div>
                    </div>

                    <div className="flex flex-col gap-1">
                      <label className="text-sm font-medium">
                        Floor of the mouth
                      </label>
                      <div className="flex flex-wrap items-center gap-2">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="checkbox"
                            className={choiceInputClass}
                            name="mouthFloorNormal"
                            checked={exam.mouthFloorNormal}
                            onChange={handleExamChange}
                          />{" "}
                          Normal
                        </label>
                        <label htmlFor="patient-mouthFloorNotes" className="text-sm font-medium">
                          Abnormal, specify
                        </label>
                        <input
                      id="patient-mouthFloorNotes"
                          type="text"
                          name="mouthFloorNotes"
                          value={exam.mouthFloorNotes}
                          onChange={handleExamChange}
                          className="border-b border-gray-300 outline-none flex-1 min-w-40"
                        />
                      </div>
                    </div>
                    <div className="flex flex-col gap-2 mt-4">
                      <div className="text-sm font-medium">Occlusion</div>
                      <div className="flex flex-wrap items-center gap-2">
                        <label htmlFor="patient-molarRelationship" className="w-40 text-sm">
                          1st Molar Relationship
                        </label>
                        <input
                      id="patient-molarRelationship"
                          type="text"
                          name="molarRelationship"
                          value={exam.molarRelationship}
                          onChange={handleExamChange}
                          className="border-b border-gray-300 outline-none flex-1 min-w-40"
                        />
                      </div>
                      <div className="flex flex-wrap items-center gap-2">
                        <label htmlFor="patient-canineRelationship" className="w-40 text-sm">Canine Relationship</label>
                        <input
                      id="patient-canineRelationship"
                          type="text"
                          name="canineRelationship"
                          value={exam.canineRelationship}
                          onChange={handleExamChange}
                          className="border-b border-gray-300 outline-none flex-1 min-w-40"
                        />
                      </div>
                      <div className="flex flex-wrap items-center gap-2">
                        <label htmlFor="patient-occlusionClassification" className="w-40 text-sm">Classification</label>
                        <input
                      id="patient-occlusionClassification"
                          type="text"
                          name="occlusionClassification"
                          value={exam.occlusionClassification}
                          onChange={handleExamChange}
                          className="border-b border-gray-300 outline-none flex-1 min-w-40"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col gap-3 mt-4">
                    <div className="flex flex-col gap-1">
                      <label className="text-sm font-medium">Gingiva</label>
                      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingiva"
                            value="normal"
                            checked={exam.gingiva === "normal"}
                            onChange={handleExamChange}
                          />{" "}
                          Normal
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingiva"
                            value="inflamed"
                            checked={exam.gingiva === "inflamed"}
                            onChange={handleExamChange}
                          />{" "}
                          Inflamed
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingiva"
                            value="receded"
                            checked={exam.gingiva === "receded"}
                            onChange={handleExamChange}
                          />{" "}
                          Receded
                        </label>
                      </div>
                    </div>

                    <div className="flex flex-col gap-1">
                      <label className="text-sm text-gray-500">Color</label>
                      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingivaColor"
                            value="coral_pink"
                            checked={exam.gingivaColor === "coral_pink"}
                            onChange={handleExamChange}
                          />{" "}
                          Coral Pink
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingivaColor"
                            value="bright_red"
                            checked={exam.gingivaColor === "bright_red"}
                            onChange={handleExamChange}
                          />{" "}
                          Bright Red
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingivaColor"
                            value="bluish_red"
                            checked={exam.gingivaColor === "bluish_red"}
                            onChange={handleExamChange}
                          />{" "}
                          Bluish Red
                        </label>
                      </div>
                    </div>

                    <div className="flex flex-col gap-1">
                      <label className="text-sm text-gray-500">Consistency</label>
                      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingivaConsistency"
                            value="firm"
                            checked={exam.gingivaConsistency === "firm"}
                            onChange={handleExamChange}
                          />{" "}
                          Firm
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingivaConsistency"
                            value="hyperplastic"
                            checked={exam.gingivaConsistency === "hyperplastic"}
                            onChange={handleExamChange}
                          />{" "}
                          Hyperplastic
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="gingivaConsistency"
                            value="smooth"
                            checked={exam.gingivaConsistency === "smooth"}
                            onChange={handleExamChange}
                          />{" "}
                          Smooth
                        </label>
                      </div>
                    </div>
                    <div className="flex flex-col gap-1 mt-2">
                      <label className="text-sm font-medium">Oral Hygiene</label>
                      <div className="flex items-center gap-4 flex-wrap">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="oralHygiene"
                            value="healthy"
                            checked={exam.oralHygiene === "healthy"}
                            onChange={handleExamChange}
                          />{" "}
                          Healthy
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="oralHygiene"
                            value="gingivitis"
                            checked={exam.oralHygiene === "gingivitis"}
                            onChange={handleExamChange}
                          />{" "}
                          Gingivitis
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="oralHygiene"
                            value="periodontitis"
                            checked={exam.oralHygiene === "periodontitis"}
                            onChange={handleExamChange}
                          />{" "}
                          Periodontitis
                        </label>
                      </div>
                      <div className="flex items-center gap-4 flex-wrap pl-4">
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hygieneSeverity"
                            value="mild"
                            checked={exam.hygieneSeverity === "mild"}
                            onChange={handleExamChange}
                          />{" "}
                          Mild
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hygieneSeverity"
                            value="moderate"
                            checked={exam.hygieneSeverity === "moderate"}
                            onChange={handleExamChange}
                          />{" "}
                          Moderate
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hygieneSeverity"
                            value="severe"
                            checked={exam.hygieneSeverity === "severe"}
                            onChange={handleExamChange}
                          />{" "}
                          Severe
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hygieneSeverity"
                            value="aggressive"
                            checked={exam.hygieneSeverity === "aggressive"}
                            onChange={handleExamChange}
                          />{" "}
                          Aggressive
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hygieneSeverity"
                            value="chronic"
                            checked={exam.hygieneSeverity === "chronic"}
                            onChange={handleExamChange}
                          />{" "}
                          Chronic
                        </label>
                      </div>
                    </div>
                    <div className="flex flex-col gap-1 mt-2">
                      <label className="text-sm font-medium">Deposits</label>
                      <div className="flex flex-wrap items-center gap-2">
                        <label className="w-12 text-sm">Soft:</label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="softDeposits"
                            value="none"
                            checked={exam.softDeposits === "none"}
                            onChange={handleExamChange}
                          />{" "}
                          None
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="softDeposits"
                            value="slight"
                            checked={exam.softDeposits === "slight"}
                            onChange={handleExamChange}
                          />{" "}
                          Slight
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="softDeposits"
                            value="moderate"
                            checked={exam.softDeposits === "moderate"}
                            onChange={handleExamChange}
                          />{" "}
                          Moderate
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="softDeposits"
                            value="severe"
                            checked={exam.softDeposits === "severe"}
                            onChange={handleExamChange}
                          />{" "}
                          Severe
                        </label>
                      </div>
                      <div className="flex flex-wrap items-center gap-2">
                        <label className="w-12 text-sm">Hard:</label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hardDeposits"
                            value="none"
                            checked={exam.hardDeposits === "none"}
                            onChange={handleExamChange}
                          />{" "}
                          None
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hardDeposits"
                            value="slight"
                            checked={exam.hardDeposits === "slight"}
                            onChange={handleExamChange}
                          />{" "}
                          Slight
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hardDeposits"
                            value="moderate"
                            checked={exam.hardDeposits === "moderate"}
                            onChange={handleExamChange}
                          />{" "}
                          Moderate
                        </label>
                        <label className={`${choiceLabelClass} text-sm`}>
                          <input
                            type="radio"
                            className={choiceInputClass}
                            name="hardDeposits"
                            value="severe"
                            checked={exam.hardDeposits === "severe"}
                            onChange={handleExamChange}
                          />{" "}
                          Severe
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </>
            )}
            {/* Diagnostic tests and consent are not stored in the database
                yet; their Save buttons only move the form along. */}
            {step === 4 && (
              <DiagnosticTests
                key={diagnosticsKey}
                onSave={() => setStep(5)}
                onDiscard={() => setDiagnosticsKey((k) => k + 1)}
              />
            )}
            {step === 5 && (
              <PatientConsent onSave={() => router.push("/dashboard")} />
            )}
          </div>
          {/* Footer buttons */}
          <div className="flex flex-wrap justify-end items-center gap-3 p-4">
            {error && <p className="text-sm text-red-600 mr-auto">{error}</p>}
            {step === 1 && (
              <button
                type="button"
                onClick={handleSubmitIntake}
                disabled={saving}
                className={`${primaryButtonClass} text-sm font-medium`}
              >
                {saving ? "Submitting..." : "Submit"}
              </button>
            )}
            {step === 3 && (
              <>
                <button
                  type="button"
                  onClick={() => setExam(EMPTY_EXAM)}
                  disabled={saving}
                  className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 disabled:opacity-50"
                >
                  Discard Changes
                </button>
                <button
                  type="button"
                  onClick={handleSaveExamination}
                  disabled={saving}
                  className={`${primaryButtonClass} text-sm font-medium`}
                >
                  {saving ? "Saving..." : "Save"}
                </button>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
